AMBARI-23469 HostCleanup.py script is failing with AttributeError: 'NoneType' object has no attribute 'get' (#3061)
Change-Id: Id07397049da792bfa2f8e9c36e19871baf385fe5
(cherry picked from commit b05961104ea272a6885d03ce6978eb03422479d4)