AMBARI-24757. Grafana start failing on U14 fails with error "AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'" (aonishuk)
(cherry picked from commit 4da9f42584e7185be7c776574ce0e15ce4cc25d5)

Change-Id: I35d5419a2feb43b199ef445f9f9ce4ad823f9152